{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-openshift-ingress-to-{{ include "bcbox.fullname" . }}-app
  labels:
    {{- include "bcbox.labels" . | nindent 4 }}
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
        - podSelector:
            matchLabels: {{ include "bcbox.selectorLabels" . | nindent 14 }}
      ports:
        - port: {{ default "8080" .Values.config.configMap.SERVER_PORT | atoi }}
          protocol: TCP
  podSelector:
    matchLabels: {{- include "bcbox.selectorLabels" . | nindent 6 }}
{{- end }}
