---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bcbox.fullname" . }}
  labels:
    {{- include "bcbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "bcbox.selectorLabels" . | nindent 4 }}
