---
config:
  enabled: true
  configMap:
    FRONTEND_APIPATH: api/v1
    FRONTEND_COMS_APIPATH: https://coms-dev.api.gov.bc.ca/api/v1
    FRONTEND_EXCLUDE_METADATA: geodrive.common.encoding,geodrive.windows.attr,geodrive.windows.secdesc,s3b-last-modified
    FRONTEND_NOTIFICATION_BANNER: This is the DEV environment of BCBox. Uploaded files may not persist and may be deleted from the COMS database as we continue development. Please do not upload personal or private information. Thank you for your understanding as we work to improve BCBox
    FRONTEND_OIDC_AUTHORITY: https://dev.loginproxy.gov.bc.ca/auth/realms/standard
    FRONTEND_OIDC_CLIENTID: bc-box-4555
    SERVER_APIPATH: /api/v1
    SERVER_BODYLIMIT: 30mb
    SERVER_CHES_APIPATH: https://ches-dev.api.gov.bc.ca/api/v1
    SERVER_CHES_TOKENURL: https://dev.loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token
    SERVER_CHES_FROM: DoNotReply.BCBox@gov.bc.ca
    # SERVER_LOGFILE: ~
    SERVER_LOGLEVEL: http
    SERVER_OIDC_AUTHORITY: https://dev.loginproxy.gov.bc.ca/auth/realms/standard
    SERVER_OIDC_IDENTITYKEY: idir_user_guid,bceid_user_guid,github_id
    SERVER_OIDC_PUBLICKEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuy7zfh2ZgpDV5mH/aXyLDTddZK81rGakJcTy4KvCNOkDDxt1KAhW02lmbCo8YhHCOzjNZBp1+Vi6QiMRgBqAe2GTPZYEiV70aXfROGZe3Nvwcjbtki6HoyRte3SpqLJEIPL2F+hjJkw1UPGnjPTWZkEx9p74b9i3BjuE8RnjJ0Sza2MWw83zoQUZEJRGiopSL0yuVej6t2LO2btVdVf7QuZfPt9ehkcQYlPKpVvJA+pfeqPAdnNt7OjEIeYxinjurZr8Z04hz8UhkRefcWlSbFzFQYmL7O7iArjW0bsSvq8yNUd5r0KCOQkFduwZy26yTzTxj8OLFT91fEmbBBl4rQIDAQAB
    SERVER_PORT: "8080"
